### ISSUE TITLE
Amazium.co.uk is offline

### ISSUE THREAD

**Issue by DavidWiesner** [MikeBallan/Amazium.co.uk#4]
Hi Mike,
a friend of mine highly recommended your framework instead of the huge bootstrap thing. I wan´t see some examples of your framework, but the website Amazium.co.uk is currently offline. Is there an other website to see your Framework in action?

regards,
David

**Comment by MikeBallan** [comment]
Hi David,

Amazium should be back now as we had to move servers, Sorry about the down time.

Mike Ballan
