### ISSUE TITLE
To use as template?

### ISSUE THREAD

**Issue by JamesFLWIlliams** [MikeBallan/Amazium.co.uk#7]
Can I use this as a template for my Amazium website?

**Comment by catchamonkey** [comment]
Do you mean a website that you are building using Amazium?

**Comment by JamesFLWIlliams** [comment]
Yes, sorry for not being too clear.

**Comment by catchamonkey** [comment]
You can't use the Amazium.co.uk site as a template no, that is a design specific for this site.

But you can use the example files are part of the main repo as a base for your site.
Those can be found at https://github.com/OwlyStuff/Amazium

Hope that helps!
